# ponytail: shared intl city/country tables for gen_location.py (keep in sync with scriptable/gen-location.js)

CITY_ZH_TO_EN: dict[str, str] = {
    "芝加哥": "Chicago", "纽约": "New York", "洛杉矶": "Los Angeles", "旧金山": "San Francisco",
    "西雅图": "Seattle", "波士顿": "Boston", "华盛顿": "Washington", "费城": "Philadelphia",
    "迈阿密": "Miami", "休斯敦": "Houston", "休斯顿": "Houston", "拉斯维加斯": "Las Vegas",
    "檀香山": "Honolulu", "夏威夷": "Honolulu", "丹佛": "Denver", "亚特兰大": "Atlanta",
    "圣地亚哥": "San Diego", "凤凰城": "Phoenix", "达拉斯": "Dallas", "奥斯汀": "Austin",
    "波特兰": "Portland", "底特律": "Detroit", "明尼阿波利斯": "Minneapolis", "新奥尔良": "New Orleans",
    "盐湖城": "Salt Lake City", "巴尔的摩": "Baltimore", "匹兹堡": "Pittsburgh", "夏洛特": "Charlotte",
    "多伦多": "Toronto", "温哥华": "Vancouver", "蒙特利尔": "Montreal", "卡尔加里": "Calgary", "渥太华": "Ottawa",
    "伦敦": "London", "曼彻斯特": "Manchester", "伯明翰": "Birmingham", "爱丁堡": "Edinburgh",
    "格拉斯哥": "Glasgow", "利物浦": "Liverpool",
    "柏林": "Berlin", "慕尼黑": "Munich", "法兰克福": "Frankfurt", "汉堡": "Hamburg",
    "科隆": "Cologne", "斯图加特": "Stuttgart", "杜塞尔多夫": "Dusseldorf",
    "巴黎": "Paris", "里昂": "Lyon", "马赛": "Marseille", "尼斯": "Nice", "波尔多": "Bordeaux",
    "罗马": "Rome", "米兰": "Milan", "威尼斯": "Venice", "佛罗伦萨": "Florence", "那不勒斯": "Naples",
    "马德里": "Madrid", "巴塞罗那": "Barcelona", "塞维利亚": "Seville",
    "东京": "Tokyo", "大阪": "Osaka", "京都": "Kyoto", "名古屋": "Nagoya", "横滨": "Yokohama",
    "札幌": "Sapporo", "福冈": "Fukuoka", "神户": "Kobe",
    "首尔": "Seoul", "釜山": "Busan",
    "悉尼": "Sydney", "墨尔本": "Melbourne", "布里斯班": "Brisbane", "珀斯": "Perth", "阿德莱德": "Adelaide",
    "奥克兰": "Auckland", "惠灵顿": "Wellington",
    "阿姆斯特丹": "Amsterdam", "布鲁塞尔": "Brussels", "苏黎世": "Zurich", "日内瓦": "Geneva",
    "维也纳": "Vienna", "斯德哥尔摩": "Stockholm", "奥斯陆": "Oslo", "哥本哈根": "Copenhagen",
    "赫尔辛基": "Helsinki", "都柏林": "Dublin", "里斯本": "Lisbon", "雅典": "Athens",
    "华沙": "Warsaw", "布拉格": "Prague", "布达佩斯": "Budapest",
    "莫斯科": "Moscow", "圣彼得堡": "Saint Petersburg", "伊斯坦布尔": "Istanbul",
    "迪拜": "Dubai", "阿布扎比": "Abu Dhabi", "特拉维夫": "Tel Aviv", "耶路撒冷": "Jerusalem",
    "开罗": "Cairo", "约翰内斯堡": "Johannesburg", "开普敦": "Cape Town",
    "新加坡": "Singapore", "曼谷": "Bangkok", "清迈": "Chiang Mai", "吉隆坡": "Kuala Lumpur",
    "雅加达": "Jakarta", "巴厘岛": "Bali", "马尼拉": "Manila", "河内": "Hanoi", "胡志明市": "Ho Chi Minh City",
    "西贡": "Ho Chi Minh City", "新德里": "New Delhi", "孟买": "Mumbai", "班加罗尔": "Bangalore", "加尔各答": "Kolkata",
    "圣保罗": "Sao Paulo", "里约热内卢": "Rio de Janeiro", "墨西哥城": "Mexico City", "坎昆": "Cancun",
    "布宜诺斯艾利斯": "Buenos Aires", "智利圣地亚哥": "Santiago",
}

CITY_ZH_TO_COUNTRY: dict[str, str] = {
    "芝加哥": "United States", "纽约": "United States", "洛杉矶": "United States", "旧金山": "United States",
    "西雅图": "United States", "波士顿": "United States", "华盛顿": "United States", "费城": "United States",
    "迈阿密": "United States", "休斯敦": "United States", "休斯顿": "United States", "拉斯维加斯": "United States",
    "檀香山": "United States", "夏威夷": "United States", "丹佛": "United States", "亚特兰大": "United States",
    "圣地亚哥": "United States", "凤凰城": "United States", "达拉斯": "United States", "奥斯汀": "United States",
    "波特兰": "United States", "底特律": "United States", "明尼阿波利斯": "United States", "新奥尔良": "United States",
    "盐湖城": "United States", "巴尔的摩": "United States", "匹兹堡": "United States", "夏洛特": "United States",
    "多伦多": "Canada", "温哥华": "Canada", "蒙特利尔": "Canada", "卡尔加里": "Canada", "渥太华": "Canada",
    "伦敦": "United Kingdom", "曼彻斯特": "United Kingdom", "伯明翰": "United Kingdom", "爱丁堡": "United Kingdom",
    "格拉斯哥": "United Kingdom", "利物浦": "United Kingdom",
    "柏林": "Germany", "慕尼黑": "Germany", "法兰克福": "Germany", "汉堡": "Germany", "科隆": "Germany",
    "斯图加特": "Germany", "杜塞尔多夫": "Germany",
    "巴黎": "France", "里昂": "France", "马赛": "France", "尼斯": "France", "波尔多": "France",
    "罗马": "Italy", "米兰": "Italy", "威尼斯": "Italy", "佛罗伦萨": "Italy", "那不勒斯": "Italy",
    "马德里": "Spain", "巴塞罗那": "Spain", "塞维利亚": "Spain",
    "东京": "Japan", "大阪": "Japan", "京都": "Japan", "名古屋": "Japan", "横滨": "Japan",
    "札幌": "Japan", "福冈": "Japan", "神户": "Japan",
    "首尔": "South Korea", "釜山": "South Korea",
    "悉尼": "Australia", "墨尔本": "Australia", "布里斯班": "Australia", "珀斯": "Australia", "阿德莱德": "Australia",
    "奥克兰": "New Zealand", "惠灵顿": "New Zealand",
    "阿姆斯特丹": "Netherlands", "布鲁塞尔": "Belgium", "苏黎世": "Switzerland", "日内瓦": "Switzerland",
    "维也纳": "Austria", "斯德哥尔摩": "Sweden", "奥斯陆": "Norway", "哥本哈根": "Denmark", "赫尔辛基": "Finland",
    "都柏林": "Ireland", "里斯本": "Portugal", "雅典": "Greece", "华沙": "Poland", "布拉格": "Czech Republic",
    "布达佩斯": "Hungary", "莫斯科": "Russia", "圣彼得堡": "Russia", "伊斯坦布尔": "Turkey",
    "迪拜": "United Arab Emirates", "阿布扎比": "United Arab Emirates", "特拉维夫": "Israel", "耶路撒冷": "Israel",
    "开罗": "Egypt", "约翰内斯堡": "South Africa", "开普敦": "South Africa",
    "新加坡": "Singapore", "曼谷": "Thailand", "清迈": "Thailand", "吉隆坡": "Malaysia", "雅加达": "Indonesia",
    "巴厘岛": "Indonesia", "马尼拉": "Philippines", "河内": "Vietnam", "胡志明市": "Vietnam", "西贡": "Vietnam",
    "新德里": "India", "孟买": "India", "班加罗尔": "India", "加尔各答": "India",
    "圣保罗": "Brazil", "里约热内卢": "Brazil", "墨西哥城": "Mexico", "坎昆": "Mexico",
    "布宜诺斯艾利斯": "Argentina", "智利圣地亚哥": "Chile",
}

FOREIGN_CITIES_ZH = "|".join(sorted(CITY_ZH_TO_EN.keys(), key=len, reverse=True))
